#
version: '3'

services:
  commerceapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
