# Generated by Django 3.0.8 on 2020-07-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='is_active',
        ),
    ]
