# Generated by Django 3.0.8 on 2020-07-28 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200724_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
        migrations.AddField(
            model_name='listing',
            name='listed_by',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
