# Generated by Django 3.0.8 on 2020-07-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200728_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateField(default="2020-07-01"),
            preserve_default=False,
        ),
    ]
